-- ============================================================
--  V5 — DOM1 Flight Ops. The leg is the root aggregate:
--  everything about a flight hangs off leg_id.
--  No value in this schema is ever generated by the product
--  (audit constat 2 — the prototype generated its schedule).
-- ============================================================
CREATE TABLE ops.trips (
    id                uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id         uuid        NOT NULL REFERENCES platform.tenants (id),
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    source_type       text        NOT NULL DEFAULT 'manual',
    source_ref        text,
    source_version    text,
    source_author     uuid,
    source_at         timestamptz NOT NULL DEFAULT now(),
    client_ref        text,
    sales_request_id  uuid,
    status            text        NOT NULL DEFAULT 'OPEN',
    CONSTRAINT ck_trips_status CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED'))
);

CREATE INDEX ix_trips_tenant ON ops.trips (tenant_id);

CREATE TABLE ops.legs (
    id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id        uuid        NOT NULL REFERENCES platform.tenants (id),
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    source_type      text        NOT NULL DEFAULT 'manual',
    source_ref       text,
    source_version   text,
    source_author    uuid,
    source_at        timestamptz NOT NULL DEFAULT now(),
    trip_id          uuid        REFERENCES ops.trips (id),
    aircraft_id      uuid        NOT NULL REFERENCES camo.aircraft (id),
    flight_no        text        NOT NULL,
    dep_icao         text        NOT NULL,
    arr_icao         text        NOT NULL,
    base_icao        text,
    std              timestamptz NOT NULL,
    sta              timestamptz NOT NULL,
    etd              timestamptz,
    eta              timestamptz,
    out_at           timestamptz,
    off_at           timestamptz,
    on_at            timestamptz,
    in_at            timestamptz,
    ctot             timestamptz,
    status           text        NOT NULL DEFAULT 'PLANNED',
    flight_type      text        NOT NULL DEFAULT 'PAX',
    pax_count        integer     NOT NULL DEFAULT 0,
    risk_level       text,
    mvt_sent_at      timestamptz,
    remark           text,
    business_key     text        NOT NULL,
    CONSTRAINT uq_legs_business_key UNIQUE (business_key),
    CONSTRAINT ck_legs_status CHECK (status IN ('PLANNED', 'PREPARED', 'RELEASED', 'DEPARTED', 'ARRIVED', 'CLOSED', 'CANCELLED')),
    CONSTRAINT ck_legs_flight_type CHECK (flight_type IN ('PAX', 'FERRY', 'POSITIONING', 'TRAINING', 'MAINTENANCE', 'AMBULANCE')),
    CONSTRAINT ck_legs_risk CHECK (risk_level IS NULL OR risk_level IN ('LOW', 'MEDIUM', 'CRITICAL')),
    CONSTRAINT ck_legs_times CHECK (sta > std)
);

CREATE INDEX ix_legs_tenant_std ON ops.legs (tenant_id, std);
CREATE INDEX ix_legs_aircraft_std ON ops.legs (aircraft_id, std);
CREATE INDEX ix_legs_status ON ops.legs (tenant_id, status);
CREATE INDEX ix_legs_trip ON ops.legs (trip_id);

COMMENT ON COLUMN ops.legs.business_key IS 'Stable key operator-registration-date-leg; never regenerated';
COMMENT ON COLUMN ops.legs.ctot IS 'Calculated take-off time received from ATFM';

CREATE TABLE ops.leg_events (
    id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id        uuid        NOT NULL REFERENCES platform.tenants (id),
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    source_type      text        NOT NULL DEFAULT 'manual',
    source_ref       text,
    source_version   text,
    source_author    uuid,
    source_at        timestamptz NOT NULL DEFAULT now(),
    leg_id           uuid        NOT NULL REFERENCES ops.legs (id),
    kind             text        NOT NULL,
    payload_before   jsonb,
    payload_after    jsonb,
    actor_id         uuid,
    reason           text,
    CONSTRAINT ck_leg_events_kind CHECK (kind IN ('CREATED', 'MOVED', 'AIRCRAFT_CHANGED', 'DELAYED', 'CANCELLED', 'RELEASED', 'MOVEMENT', 'CLOSED', 'REMARK'))
);

CREATE INDEX ix_leg_events_leg ON ops.leg_events (leg_id, created_at DESC);

CREATE TABLE ops.releases (
    id                    uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id             uuid        NOT NULL REFERENCES platform.tenants (id),
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    source_type           text        NOT NULL DEFAULT 'manual',
    source_ref            text,
    source_version        text,
    source_author         uuid,
    source_at             timestamptz NOT NULL DEFAULT now(),
    leg_id                uuid        NOT NULL REFERENCES ops.legs (id),
    version               integer     NOT NULL DEFAULT 1,
    signed_by             uuid,
    signed_at             timestamptz,
    derogation            boolean     NOT NULL DEFAULT false,
    derogation_reason     text,
    blocking_checks       jsonb,
    dossier_document_id   uuid,
    captain_ack_by        uuid,
    captain_ack_at        timestamptz,
    CONSTRAINT uq_releases_leg_version UNIQUE (leg_id, version),
    CONSTRAINT ck_releases_derogation CHECK (derogation = false OR derogation_reason IS NOT NULL)
);

CREATE TABLE ops.delay_codes (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       uuid        NOT NULL REFERENCES platform.tenants (id),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    source_type     text        NOT NULL DEFAULT 'refdata',
    source_ref      text,
    source_version  text,
    source_author   uuid,
    source_at       timestamptz NOT NULL DEFAULT now(),
    code            text        NOT NULL,
    label           text        NOT NULL,
    active          boolean     NOT NULL DEFAULT true,
    CONSTRAINT uq_delay_codes UNIQUE (tenant_id, code)
);

CREATE TABLE ops.delay_records (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       uuid        NOT NULL REFERENCES platform.tenants (id),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    source_type     text        NOT NULL DEFAULT 'manual',
    source_ref      text,
    source_version  text,
    source_author   uuid,
    source_at       timestamptz NOT NULL DEFAULT now(),
    leg_id          uuid        NOT NULL REFERENCES ops.legs (id),
    minutes         integer     NOT NULL,
    code            text        NOT NULL,
    sub_code        text,
    remark          text,
    CONSTRAINT ck_delay_minutes CHECK (minutes > 0)
);

CREATE INDEX ix_delay_records_leg ON ops.delay_records (leg_id);

CREATE TABLE ops.alerts (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       uuid        NOT NULL REFERENCES platform.tenants (id),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    source_type     text        NOT NULL DEFAULT 'engine',
    source_ref      text,
    source_version  text,
    source_author   uuid,
    source_at       timestamptz NOT NULL DEFAULT now(),
    leg_id          uuid        REFERENCES ops.legs (id),
    severity        text        NOT NULL,
    rule            text        NOT NULL,
    cause           text        NOT NULL,
    target_role     text,
    acked_by        uuid,
    acked_at        timestamptz,
    escalated_at    timestamptz,
    CONSTRAINT ck_alerts_severity CHECK (severity IN ('INFO', 'ATTENTION', 'CRITICAL'))
);

CREATE INDEX ix_alerts_open ON ops.alerts (tenant_id, severity) WHERE acked_at IS NULL;
